### ISSUE TITLE
QQ登录可以成功调用并显示，但是点击登录却QQ提示:"网络异常，请稍后重试"

### ISSUE THREAD

**Issue by magicalapp** [BarefootBKK/QQLoginForAndroid#2]
有什么解决方案吗?

**Comment by magicalapp** [comment]
我联系方式qq:2314815201，如果看到有空的话可以联系我吗？

**Comment by BarefootBKK** [comment]
你manifest里加了网络权限了吗？你检查下



发自&nbsp;BKK


------------------ 原始邮件 ------------------
发件人: 9292922 <notifications@github.com&gt;
发送时间: 2020年10月19日 20:49
收件人: BarefootBKK/QQLoginForAndroid <QQLoginForAndroid@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[BarefootBKK/QQLoginForAndroid] QQ登录可以成功调用并显示，但是点击登录却QQ提示:"网络异常，请稍后重试" (#2)





 
我联系方式qq:2314815201，如果看到有空的话可以联系我吗？

**Comment by magicalapp** [comment]
> 你manifest里加了网络权限了吗？你检查下 发自&nbsp;BKK
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 9292922 <notifications@github.com&gt; 发送时间: 2020年10月19日 20:49 收件人: BarefootBKK/QQLoginForAndroid <QQLoginForAndroid@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[BarefootBKK/QQLoginForAndroid] QQ登录可以成功调用并显示，但是点击登录却QQ提示:"网络异常，请稍后重试" (#2) 我联系方式qq:2314815201，如果看到有空的话可以联系我吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，这个是已经添加了的，微信支付，微信登录，支付宝支付都已经对接成功了的，QQ登录库是按照readme步骤就行了吗?不需要下载腾讯的库了吧

**Comment by magicalapp** [comment]
![image](https://user-images.githubusercontent.com/25112746/96459281-89992500-1254-11eb-97e0-40e734e1c887.png)

**Comment by BarefootBKK** [comment]
照片看不到诶

**Comment by 876870023** [comment]
开发者，你好，我也遇到网络异常问题。使用在QQ互联申请AppId的QQ可以正常登陆，其他QQ都无法登陆， 提示网络异常。不知道有什么好的解决方法，谢谢了。  邮箱：712372884@qq.com

**Comment by BarefootBKK** [comment]
您好，我这边自己测试了一下，是可以正常运行的，我用的机型是小米5 Android 8，可能型号稍微有点老了，您可以参考一下我写的demo，或者您可以详细提供一下您的登录代码逻辑吗？我目前定位是没复现当前所提及的问题，或者可以联系我的邮箱bk.he@qq.com



发自&nbsp;BKK


------------------ 原始邮件 ------------------
发件人: 876870023 <notifications@github.com&gt;
发送时间: 2020年10月24日 20:53
收件人: BarefootBKK/QQLoginForAndroid <QQLoginForAndroid@noreply.github.com&gt;
抄送: 夏日云泊镇 <2206742764@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[BarefootBKK/QQLoginForAndroid] QQ登录可以成功调用并显示，但是点击登录却QQ提示:"网络异常，请稍后重试" (#2)





 
开发者，你好，我也遇到网络异常问题。使用在QQ互联申请AppId的QQ可以正常登陆，其他QQ都无法登陆， 提示网络异常。不知道有什么好的解决方法，谢谢了。  邮箱：712372884@qq.com

**Comment by 876870023** [comment]
我测试了一下，我注册的是QQ互联里面的个人开发者  是这个原因吗，我试了你的demo确实是没问题的。

**Comment by BarefootBKK** [comment]
不排除是appId的原因，README最底下有一个APP ID的申请链接，您尝试一下换一个新的app id再尝试看看~



发自&nbsp;BKK


------------------ 原始邮件 ------------------
发件人: 876870023 <notifications@github.com&gt;
发送时间: 2020年10月24日 23:06
收件人: BarefootBKK/QQLoginForAndroid <QQLoginForAndroid@noreply.github.com&gt;
抄送: 夏日云泊镇 <2206742764@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[BarefootBKK/QQLoginForAndroid] QQ登录可以成功调用并显示，但是点击登录却QQ提示:"网络异常，请稍后重试" (#2)





 
我测试了一下，我注册的是QQ互联里面的个人开发者  是这个原因吗，我试了你的demo确实是没问题的。
